### ISSUE TITLE
Build error on nightlies

### ISSUE THREAD

**Issue by MahdiBM** [soto-project/soto-core#633]
soto-core no longer builds on Swift 6.1 / 6.2 (main) nightlies.

There is a compilation error complaining about [this line](https://github.com/soto-project/soto-core/blob/d2b2726eb7ef7f054b64264cf2e1884a3182e4a9/Sources/SotoCore/Encoder/CodableProperties/DateCoders.swift#L112) not being concurrency safe.

```swift
public static let dateFormatter = createDateFormatter()
```

Perhaps it should use `@nonisolated(unsafe)` like the other formatters above it are doing.

**Comment by MahdiBM** [comment]
@adam-fowler can you try a macOS nightly toolchain as well? That's what I'm using.

**Comment by adam-fowler** [comment]
> [@adam-fowler](https://github.com/adam-fowler) can you try a macOS nightly toolchain as well? That's what I'm using.

Is that main or 6.1? Also what date?

**Comment by MahdiBM** [comment]
Doesn't matter just the latest.
IIRC 10th January main, or 23rd 6.1.

**Comment by adam-fowler** [comment]
A PR would be much appreciated. Not finding much time at the moment.

**Comment by vsarunas** [comment]
@adam-fowler , I have opened up https://github.com/soto-project/soto-core/pull/639 as running into this as well.
