### ISSUE TITLE
type 'HTTPClient' does not conform to protocol 'AWSHTTPClient'

### ISSUE THREAD

**Issue by RaesakAce** [soto-project/soto-core#519]
**Describe the bug**
When building the project using swift version >= 5.6  you get the following errors

```
~/soto-core/Sources/SotoCore/HTTP/AsyncHTTPClient.swift:21:1: error: type 'HTTPClient' does not conform to protocol 'AWSHTTPClient'
extension AsyncHTTPClient.HTTPClient: AWSHTTPClient {
^
~/soto-core/.build/checkouts/async-http-client/Sources/AsyncHTTPClient/HTTPClient.swift:198:33: note: candidate has non-matching type '(DispatchQueue, @escaping @Sendable (Error?) -> Void) -> ()'
    @preconcurrency public func shutdown(
                                ^
~/soto-core/Sources/SotoCore/HTTP/AWSHTTPClient.swift:57:10: note: protocol requires function 'shutdown(queue:_:)' with type '(DispatchQueue, @escaping (Error?) -> Void) -> ()'
    func shutdown(queue: DispatchQueue, _ callback: @escaping (Error?) -> Void)
         ^
```

**To Reproduce**
Build with swift version >= 5.6 

**Expected behavior**
The project builds without errors

**Setup (please complete the following information):**
 - OS: endeavour-os
 - swift-version: 5.6
**Additional context**

**Comment by adam-fowler** [comment]
Duplicate of https://github.com/soto-project/soto/issues/621
Fixed by #518
